spring:
  config:
    activate:
      on-profile: dev
  http:
    encoding:
      charset:
        UTF-8
      enabled:
        true
      force:
        true
  #  datasource:
  #    url: jdbc:mariadb://13.125.177.52:3306/taskgrow
  #    username: root
  #    password: 1234
  #    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: db
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
springdoc:
  api-docs:
    path: /resource/static/v3/api-docs
  swagger-ui:
    path: /resource/static/swagger
    config-url: /resource/static/v3/api-docs/swagger-config
    url: /resource/static/v3/api-docs
    disable-swagger-default-url: true
