name: TaskGrow Client CI

on:
  push:
    branches: ['main']
    paths:
      - 'app-client/**'
      - '.github/workflows/client-CI.yml'
  pull_request:
    paths:
      - 'app-client/**'
      - '.github/workflows/client-CI.yml'

defaults:
  run:
    working-directory: ./app-client

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: 'npm'
          cache-dependency-path: app-client/package-lock.json
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: app-client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app-client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app-client/package-lock.json') }}
      - name: Install dependecies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - run: npm run build
      - run: npm run lint
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.TASKGROW_DOCKER_USERNAME }}
          password: ${{ secrets.TASKGROW_DOCKER_TOKEN }}
          logout: true
      - name: Docker build
        if: github.ref == 'refs/heads/main'
        run: docker build . -t lkw2v/taskgrow-client --platform linux/amd64 -f Dockerfile
      - name: Docker push
        run: docker push lkw2v/taskgrow-client
