name: TaskGrow Server CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "app-server/**"
      - ".github/workflows/server-CI.yml"
  pull_request:
    paths:
      - ".github/workflows/server-CI.yml"
permissions:
  contents: read
defaults:
  run:
    working-directory: ./app-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: gradle Assemble
      run: ./gradlew assemble

    - name: Docker build
      if: github.ref == 'refs/heads/main'
      run: docker build . --build-arg DEPENDENCY=build/dependency -t lkw2v/task-grow --platform linux/amd64

    - name: Docker push
      if: github.ref == 'refs/heads/main'
      run: |
        docker login -u lkw2v -p ${{ secrets.TASKGROW_DOCKER_TOKEN }}
        docker push lkw2v/task-grow
 
