name: TaskGrow Server Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "app-server/**"
      - ".github/workflows/server-CI.yml"
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: cd app-server && chmod +x gradlew
      
    - name: Run build with Gradle wrapper
      uses: gradle/gradle-build-action@v2
      with:
        arguments: app-server:build
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
    - name: Docker build
      if: github.ref == 'refs/heads/main'
      run: docker build . -t lkw2v/task-grow:${GITHUB_SHA::7}
    
    - name: Docker push
      if: github.ref == 'refs/heads/main'
      run: |
        docker login -u lkw2v -p ${{ secrets.TASKGROW_DOCKER_TOKEN }}
        docker push lkw2v/task-grow:${GITHUB_SHA::7}
 
