name: TaskGrow Server CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "app-server/**"
      - ".github/workflows/server-CI.yml"
  pull_request:
    paths:
      - ".github/workflows/server-CI.yml"
permissions:
  contents: read
defaults:
  run:
    working-directory: ./app-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: gradle Build
      run: ./gradlew build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.TASKGROW_DOCKER_USERNAME }}
        password: ${{ secrets.TASKGROW_DOCKER_TOKEN }}
        logout: true

    - name: Docker build
      run: docker build . -t lkw2v/task-grow --platform linux/amd64

    - name: Docker push
      run: docker push lkw2v/task-grow
